### PR TITLE
feat: optimize font load using self-hosted variable fonts

### LINKED ISSUE #664: Explore a better font loading mechanism
## Description

One of our problematic loading in initial load is our `Inter Font`

Screen Shot 2021-08-12 at 21 41 04

There are several things need to tackle:

1. Since font are rarely change, should we treat as static file without `hashing`? Hashing will remove the cache in every deployment.
2. Find a way how to preload this request, since it will be used immediately so we need to preload the request.

## Tasks

- [ ] ...
- [ ] ...
- [ ] ...

### PR DESCRIPTION
**Pull request by svspicious**
Closes #664

## Description

Replace `typeface-inter` with smaller variable fonts used in here https://vercel.com/design/text
Add cache control and preload the fonts

## Current Tasks

- [x] Remove `typeface-inter` package
- [x] Define font-face from css
- [x] Add cache control
- [x] Preload the fonts

### CODE REVIEW

**Comment by zainfathoni** [comment]
Apparently, the [performance check is failing](https://github.com/kawalcovid19/wargabantuwarga.com/pull/694/checks?check_run_id=3319509306) 😅.

Let me rerun it to see if it's just an intermittent issue or not.

**Comment by zainfathoni** [comment]
The Lighthouse check failures seem to persist.

[This is the report from web.dev/measure](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fdeploy-preview-694--wargabantuwarga.netlify.app).

Do you have any insights, Mas @mazipan? 😁

**Comment by mazipan** [comment]
https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/troubleshooting.md#im-seeing-differences-in-the-results-even-though-i-didnt-change-anything

**Comment by mazipan** [comment]
```

Uploading median LHR of https://deploy-preview-694--wargabantuwarga.netlify.app/...success!
Open the report at https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1628841065237-51767.report.html
Uploading median LHR of https://deploy-preview-694--wargabantuwarga.netlify.app/tentang-kami...success!
Open the report at https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1628841065934-96994.report.html
Uploading median LHR of https://deploy-preview-694--wargabantuwarga.netlify.app/donasi...success!
Open the report at https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1628841066334-73134.report.html
Uploading median LHR of https://deploy-preview-694--wargabantuwarga.netlify.app/faq...success!
Open the report at https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1628841066930-22612.report.html
Uploading median LHR of https://deploy-preview-694--wargabantuwarga.netlify.app/provinces...success!
Open the report at https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1628841067629-66180.report.html

```

**Review by mazipan — APPROVED** [review]
LGTM 🚢

**Comment by svspicious** [comment]
Maybe because the github-action also
image

for the reference, this run doesn't have warning

https://github.com/kawalcovid19/wargabantuwarga.com/runs/3319516608?check_suite_focus=true
image

**Comment by mazipan** [comment]
That's why, we need to run more than once, to get the median score.

**Comment by zainfathoni** [comment]
> Maybe because the github-action also

Even when we run it on web.dev/measure, the results are not always consistent. 😅

**Pull request merged**
