### PR TITLE
feat: add 'ketersediaan' field to sheet

### LINKED ISSUE #600: Display the new `Ketersediaan` field from the database
## Description

From now on, our database team has dedicated volunteers to update the availability of COVID-19-related services, such as **Oksigen**, **Tempat Isoman**, **Bantuan Kebutuhan Pokok**, and **Tempat Vaksin**.

We need to reflect the values from the last column (`Ketersediaan`) in the [database sheets](https://kcov.id/wbw-sheets) into our `Province` and `Contact` pages.

### Additional Context

[Slack thread](https://kawalcovid19.slack.com/archives/C0279E2Q99Q/p1627620878006200)

Screenshot 2021-08-09 at 10 26 35

### Data Source

Fetch the values from the last column in the [database sheets](https://kcov.id/wbw-sheets)

Screenshot 2021-08-09 at 10 31 44
Screenshot 2021-08-09 at 10 31 29

### `Province` Page

Add another tag besides the `Kebutuhan` tag.

- if `Tersedia`, add a `green` tag,
- else if `Tidak Tersedia`, add a `red` tag,
- else add nothing.

Screenshot 2021-08-09 at 10 29 35

### `Contact` Page

Add a new description row indicating `Ketersediaan`. Hide the row if it's empty.

Screenshot 2021-08-09 at 10 36 49

## Tasks

- [ ] Update the [fetch-sheets.ts](https://github.com/kawalcovid19/wargabantuwarga.com/blob/b190024d3beeba67a569149208b7c236f6d3e5ad/etc/fetchers/fetch-sheets.ts) implementation to add the last column
- [ ] Update the [Contact type definition](https://github.com/kawalcovid19/wargabantuwarga.com/blob/d51b003088004be1c72d35b33b962ed2e7b2e5ae/lib/data/provinces.ts#L12-L26)
- [ ] Render the new tag in the `Province` page accordingly
- [ ] Render the new row in the `Contact` page accordingly
- [ ] Fix the broken tests accordingly
- [ ] Write more tests to cover the newly introduced cases

### PR DESCRIPTION
**Pull request by Namchee**
Closes #600 

## Description

This pull request adds `ketersediaan` on sheet data and updates the corresponding UI.

## Current Tasks

- [x] Update the fetch-sheets.ts implementation to add the last column
- [x] Update the Contact type definition
- [x] Render the new tag in the Province page accordingly
- [x] Render the new row in the Contact page accordingly
- [x] Fix the broken tests accordingly
- [x] Write more tests to cover the newly introduced cases

### CODE REVIEW

**Comment by Namchee** [comment]
What else should I test? I have tested all new features introduced in this PR, yet `codecov` checks never pass.

**Comment by mazipan** [comment]
Maybe the additional codes on `etc/fetchers`?

**Comment by Namchee** [comment]
Since the old code is hard to test due to how it's structured, I've curried the reducer. I hope that won't become an issue!

**Comment by mazipan** [comment]
Screenshot_20210811-184859_Chrome

Seems weird if the contact have long name.

https://deploy-preview-606--wargabantuwarga.netlify.app/provinces/dki-jakarta

**Comment by Namchee** [comment]
@mazipan. In my opinion it stills feel cluttered no matter if it's ordered in column or not 😅 

I think we have 3 options:

1. Remove `ketersediaan` badge for small screen users.
2. Just keep it as it is.
3. Arrange it on single column for small screen users.

For option 3, we need to determine:

1. Breakpoints when the rows are displayed into 2 columns.
2. Should the badge grow to fill the container or not.
3. If the badge isn't going to grow, where the badge is aligned.

Below is the alternative between option 2 and 3

<p style="display:flex">
phone
phone_2
</p>

I think we should consult to UI designers about this

**Review by mazipan — APPROVED** [review]
All good from me, wait other contributors give their approval

**Comment by mazipan** [comment]
We will tackle the UI problem later ya @Namchee 
Will try to ship this soon 🙏

**Pull request merged**
