### PR TITLE
fix: replace rounded-md with rounded-t-md

### LINKED ISSUE #764: Remove unnecessary border radius
## Description

- Open homepage on https://www.wargabantuwarga.com/
- Scroll to the section "Donasi warga terdampak"
- Check the border radius for the image

Screenshot_20210818-194012_Chrome

## Expected Behaviour

The border radius should only applied to the top left and top right.

### PR DESCRIPTION
**Pull request by Namchee**
Closes #764 

## Description

This pull request fixes unnecessary image rounding by replacing `rounded-md` with `rounded-t-md` in `DonationCard` component.

### CODE REVIEW

**Comment by Namchee** [comment]
Hmm, I don't get what's happening here. It seems that the CI/CD fails to find `package.json`?

**Comment by mazipan** [comment]
Seems the cache didn't work properly.

**Comment by Namchee** [comment]
I'll wait for `main` to be updated then, I don't know what else needs change for #764 😅

**Comment by mazipan** [comment]
Usually I will add a dummy commit, just to re-trigger CI with different commit hash

**Comment by Namchee** [comment]
It suddenly reruns by itself and passed by itself. I seriously don't know what's happening 😅

**Comment by mazipan** [comment]
I do re-run all the jobs

**Review by mazipan — APPROVED** [review]

**Pull request merged**
