### PR TITLE
fix: move mobile navigation to the top

### LINKED ISSUE #498: Incorrect navigation menu layout
## Description

Based on the Figma file, the navigation menu should be located at the top of the page on both mobile and desktop, hovever it is currently located at the bottom on the mobile site.

image

## Expected Behaviour

The navigation menu should be located at the top navbar on both desktop and mobile, as shown in design.

image

image

### PR DESCRIPTION
**Pull request by resir014**
Closes #498 

## Description

Moves the mobile navigation menu to the correct position.

### CODE REVIEW

**Comment by baraeb92** [comment]
The loading indicator on the top right side seems misaligned with the hamburger menu icon. 

Is it intentional? @resir014

**Comment by resir014** [comment]
@baraeb92 That is built into `nprogress` (our progress bar library) by default. It can be disabled if you want.

**Review by mazipan — APPROVED** [review]
Also looks good to me 🚀

**Comment by baraeb92** [comment]
I have no strong opinion about it sih.

I personally prefer is loading indicator is shown on the middle of the screen (noticable for the user) 

But since our website is rendering the page blazing fast, I supposed having this on top wouldn't matter much (in fact we almost doesn't need to have any loading indicator given the speed of page load) 

So we just merged this ticket, and rethink about this minor visual problem later. 

@resir014

**Review by baraeb92 — APPROVED** [review]

**Review by zainfathoni — APPROVED** [review]
LGTM 💯 

Unfortunately, it doesn't look good to `codecov/project` 😆
So please sort this out, @resir014. 😁
Thanks! 🙏

Just let me know if you need my help, because we need to cover more code outside of your changes to bump the number up. 😅

**Pull request merged**
