### PR TITLE
chore(ui): add new welcome message to support website 2.0

### PR DESCRIPTION
**Pull request by mazipan**
Partial task for #322 

## Description

Add new collection to be used later

Admin preview: https://deploy-preview-437--wargabantuwarga.netlify.app/admin

## CMS

- [x] Create new collection `welcome_message`
- [x] Field `last_updated_time` using datetime
- [x] Field `title` using string
- [x] Field `body` using Markdown
- [x] Output on `_content/welcome-message.md`

Title: `Halo Warga,`
Body markdown:

```md
Website ini adalah kumpulan berbagai informasi seputar COVID-19 di Indonesia yang didapatkan relawan melalui pencarian di internet atau media sosial.

Semangat **#WargaBantuWarga** adalah memudahkan publik mencari dan mengakses informasi terkait Covid-19 dan kontak fasilitas/alat kesehatan. Namun, karena keterbatasan kami, database yang ada di **#WargaBantuWarga** belum diverifikasi secara langsung di lapangan.

Anda bebas menggunakan dan menyebarluaskan informasi yang ada dalam website ini.
```

## UI

- [x] Add new file: the dialog and the wrapper
- [x] Trigger open the modal when the wrapper is intersecting
- [x] Add LocalStorage and set the value after the dialog close
- [x] Prevent to open dialog, when the Storage present
- [x] Add share functionality, using native share, fallback to twitter share

Screen Shot 2021-07-27 at 13 58 39

## Testing

WIP

### CODE REVIEW

**Comment by mazipan** [comment]
Need help to review this @zainfathoni 

I need this on the `main` first, to check on the CMS then going to the next task

**Comment by zainfathoni** [comment]
> Need help to review this @zainfathoni
> 
> I need this on the `main` first, to check on the CMS then going to the next task

You don't need to get it merged to the `main` first, Mas @mazipan, you can use the deploy preview link to test the CMS.

https://deploy-preview-437--wargabantuwarga.netlify.app/admin

Reference: https://www.netlifycms.org/docs/add-to-your-site/#accessing-the-cms

> Note: No matter where you access Netlify CMS — whether running locally, in a staging environment, or in your published site — it always fetches and commits files in your hosted repository (for example, on GitHub), on the branch you configured in your Netlify CMS config.yml file. This means that content fetched in the admin UI matches the content in the repository, which may be different from your locally running site. It also means that content saved using the admin UI saves directly to the hosted repository, even if you're running the UI locally or in staging.

**Comment by mazipan** [comment]
Bikin testing nya PR nih 😂
Gak sempet2 pegang nih 😴

**Comment by zainfathoni** [comment]
> Bikin testing nya PR nih 😂
> Gak sempet2 pegang nih 😴

I think I can help you with that 😁

**Comment by zainfathoni** [comment]
> I think I can help you with that 😁

I can only work on the test after getting #363 merged, so I'll try to work on it first.

**Review by zainfathoni — APPROVED** [review]
LGTM 💯 

Test coverage is also good enough now, let's ship it! 🚢

**Comment by mazipan** [comment]
Thank you @zainfathoni 

Still finding the best time to open the laptop and coding again for WBW.
For now, only watching the issues page 😂

**Comment by zainfathoni** [comment]
> Thank you @zainfathoni 
> 
> 
> 
> Still finding the best time to open the laptop and coding again for WBW.
> 
> For now, only watching the issues page 😂

No problem, Mas @mazipan. I learnt a lot of things from testing you implementation. 😁🙏

**Pull request merged**
