### PR TITLE
simplify search + filter UI

### LINKED ISSUE #244: Simplify search + filter UI
Blocks #134 

## Description

Currently our search + filter UI is a bit messy, and takes up a huge part of the screen. Rework our search UI so that it takes up less space at the top, and allow us to implement something like #134 with a better UX.

## Implementation Model

We can use an approach made by GitHub's mobile web on how they arrange their search + filter UI for issues. We can hide all the filters behind a popup where all the detailed filter options can live.

https://user-images.githubusercontent.com/6315466/126420178-2ed315fc-ee12-476d-a77f-621ee8c6685b.MOV

Dialog state can be controlled by [Headless UI](https://headlessui.dev/react/dialog). ([bundlephobia](https://bundlephobia.com/package/@headlessui/react@1.3.0))

## Tasks

- [ ] Implement filter dialog in Search UI
- [x] #347

### PR DESCRIPTION
**Pull request by resir014**
Closes #244

## Description

Adds a new UI for the search and filter form.

**Mobile**

image

**Desktop**

image

## Current Tasks

- [x] Redesign search + filter UI
- [ ] Debug slow response time for modal

### CODE REVIEW

**Comment by resir014** [comment]
So I'm running into some issue here. We already have the filter modal ready, but for some reason if we click the "Filter" button, the modal takes quite a long time to show up, but when I try to dismiss it, it does so instantly.

Here's a demo captured from my stream: https://clips.twitch.tv/TsundereLuckyZebraKappaClaus-A3I-Zmjk0DBi2H4m

Anyone have any idea why is this happening? Is this due to the apropcalypse situation in `SearchForm`?

@zainfathoni

**Comment by zainfathoni** [comment]
> So I'm running into some issue here. We already have the filter modal ready, but for some reason if we click the "Filter" button, the modal takes quite a long time to show up, but when I try to dismiss it, it does so instantly.
> 
> Here's a demo captured from my stream: https://clips.twitch.tv/TsundereLuckyZebraKappaClaus-A3I-Zmjk0DBi2H4m
> 
> Anyone has any idea why is this happening? Is this due to the apropcalypse situation in `SearchForm`?
> 
> @zainfathoni

I tried profiling the performance, and the flame chart looks pretty deep due to `lunr` function (used by `itemsjs` I guess). Therefore, I think one way of optimizing it is by calling whatever `itemsjs` is doing upfront before rendering the modal.

Screenshot 2021-07-25 at 07 42 04

However, the biggest culprit here is the `ContactList` component, so we definitely need to optimize the way it renders, maybe by memoizing some expensive values.

Screenshot 2021-07-25 at 07 44 07

**Comment by zainfathoni** [comment]
After some memoization here and there, I managed to reduce the first-load time of the modal from ~571ms to ~420ms

Before:
Screenshot 2021-07-25 at 08 37 15

After:
Screenshot 2021-07-25 at 08 35 10

and for subsequent load time, it's significantly reduced into ~193ms:

Screenshot 2021-07-25 at 08 35 16

I think we're good to go for now.

**Review by zainfathoni — APPROVED** [review]
For the first iteration, it looks good to me. 💯

When we eventually migrate to Typesense at #374, the performance must be improved because we're not relying on `itemsjs` anymore and we can preload the filtering options upfront before the user clicks the `Filter` button.

**Comment by zainfathoni** [comment]
[In production](https://www.wargabantuwarga.com/provinces/dkijakarta-1), it doesn't seem that bad, though. The first load was ~221ms, and the subsequent load was ~86ms.

Screenshot 2021-07-25 at 09 34 21
Screenshot 2021-07-25 at 09 34 34

**Comment by zainfathoni** [comment]
However, in the heavier provinces such as `Jawa Timur`, where it has 400+ entries, it is definitely slower.
First load: ~422ms
Subsequent load: ~107ms

Screenshot 2021-07-25 at 09 36 57
Screenshot 2021-07-25 at 09 37 09

**Pull request merged**
