### PR TITLE
feat: Add static slug for province detail page 

### LINKED ISSUE #288: Static slug for province detail page
## Description

Currently, we generate a slug based on the index and this can be changed everytime.

We need to set a static slug for this.

See the detail on the Doc on section 1.2.3:

https://docs.google.com/document/d/1im7CF8XaF4yYQ_jJjjW7dOKZz8tJFvidtW7bOlqt1Y8/edit?usp=sharing

## Tasks

- [ ] Generate slug from the `etc/fetcher`, slugify the title, e.g: `DKI Jakarta` will be `dki-jakarta`
- [ ] Use the slug on the client side, without any additional index
- [ ] Test the functionality

### PR DESCRIPTION
**Pull request by Namchee**
Closes #288

## Description

Generate static slugs for all provinces and apply all related changes to the client side code.

## Current Tasks

- [x] Generate slug from the etc/fetcher, slugify the title, e.g: DKI Jakarta will be dki-jakarta
- [x] Use the slug on the client side, without any additional index
- [x] Test the functionality

### CODE REVIEW

**Comment by Namchee** [comment]
This PR is waiting for #313 to be resolved first, as slug generation depends on `getKebabCase`

**Comment by zainfathoni** [comment]
> This PR is waiting for #313 to be resolved first, as slug generation depends on `getKebabCase`

#313 has been merged, @Namchee, so you can continue working on this PR.
Thanks!

**Comment by zainfathoni** [comment]
Please fix the CI checks, @Namchee, thanks! 🙏

**Comment by Namchee** [comment]
@zainfathoni the netlify build will always fail since I added a new static property `slug` when generating data with `etc/fetchers`. The new format isn't generated when netlify executes `yarn build` which will cause `provinceSlug` to be `undefined` thus causing `next build` to throw errors (as it expects the slug to be at least `null` or empty string).

Can we make sure that the app fetches fresh data before any build?

**Comment by zainfathoni** [comment]
> @zainfathoni the netlify build will always fail since I added a new static property `slug` when generating data with `etc/fetchers`. The new format isn't generated when netlify executes `yarn build` which will cause `provinceSlug` to be `undefined` thus causing `next build` to throw errors (as it expects the slug to be at least `null` or empty string).
> 
> Can we make sure that the app fetches fresh data before any build?

You can temporarily revert [this line](https://github.com/kawalcovid19/wargabantuwarga.com/commit/81be7ad788d76a02107e896fc3c14f95b124b89b#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R14) into using the `fetch-wbw` script again, so that we can merge this PR to the `main` branch.
Once it has been merged to the `main` branch, the `mirror-box` script gets the latest version of your `fetch-wbw.js` implementation after a few minutes. After that, you can raise another PR to revert your changes to use the `mirror-box` again. 😅 

I know it's a hassle, but I don't think we need to optimize this workflow, because #374 is coming soon anyway, and it will render both `fetch-wbw` and `mirror-box` useless. 😅

**Comment by Namchee** [comment]
Side note: The test is really minimal, just to pass `codecov`. I'll put other tests if we have guidelines for it.

**Review by zainfathoni — APPROVED** [review]
LGTM 💯 

Thanks for working on it, @Namchee! 🙏

**Comment by zainfathoni** [comment]
I just created a new issue #412 to revert back the one-line change you made to get this PR merged, @Namchee. 😁

**Comment by zainfathoni** [comment]
> This PR is waiting for #313 to be resolved first, as slug generation depends on `getKebabCase`

Once my #394 PR is merged, you can work on it to close the #413 ticket. 😁

**Pull request merged**
