### PR TITLE
refactor: add internal page components + use it across the site

### LINKED ISSUE #624: Finalise page layout cleanups
## Description

Refactor all page components to closely follow the Figma guidelines.

### PR DESCRIPTION
**Pull request by resir014**
Closes #624

## Description

Added special page components for "internal pages" - that is, pages that exist for content purposes.

How it looks:

image

image

image

## Tasks

- [x] Refactor page components into "internal page" components
- [x] Implement it in pages that need it
- [x] Wait until #588 is merged and re-implement it with the new component setup

### CODE REVIEW

**Review by mazipan — APPROVED** [review]
Ah looks better 🚀

**Comment by mazipan** [comment]
What about #540 ?

**Comment by mazipan** [comment]
I will waiting for this to work on Education Page and Konseling Page.
This is a better structure

**Comment by resir014** [comment]
> What about #540?

@mazipan Yes, that also blocks this PR. Will add it to the first post.

**Comment by mazipan** [comment]
How if we merge this first, and the other page follow changes from this PR @resir014 
Just afraid the blocker can not speed up the process to merge their PR.
At least we do our part.

**Comment by mazipan** [comment]
Yes, +1 from me.
We do our part, it's their risk that the PR is not fast moving.

I think this PR is very valuable, the longer we merge, we fill face more blocker.

Let's ship this ASAP.
Then we can ask other page to follow later.

**Pull request merged**
