### PR TITLE
Implement `@tailwindcss/typography` integration

### LINKED ISSUE #109: Utilise `@tailwindcss/typography` to improve the existing Google Docs page user experience.
https://tailwindcss-typography.netlify.app

### PR DESCRIPTION
**Pull request by zainfathoni**
Closes #109

## Current Tasks

- [x] Install `@tailwindcss/typography`
- [x] Implement it at the Netlify CMS home page
- [ ] ~Implement it at the Google Docs home page~
- [ ] ~#118~

### CODE REVIEW

**Comment by zainfathoni** [comment]
I tried applying the `prose` class into the `index.tsx` page and it looks like this 😅 

Do you have any idea to improve it @resir014 ? 😁 

Screenshot 2021-07-17 at 20 17 13

**Comment by resir014** [comment]
@zainfathoni Additional styles being injected from the gdocs really didn't help. `@tailwindcss/typography` needs a clean, unstyled HTML for it to work. Can we remove these in any way?

image

**Comment by zainfathoni** [comment]
Yes, we can. Just remove the css part from the JSON that we injected to the index.tsx page

**Review by resir014 — APPROVED** [review]

**Comment by ekafyi** [comment]
Quick note/comment: Is it possible to skip the "reset" styling for this part?

Screen Shot 2021-07-18 at 00 18 47

It's impossible to style it from our side because the markup _does not use nested list_. Each doctor's name and their contact & schedule info are in separate `<ul>`.

Example of first list item: (simplified)

```html
<ul>
  <li>dr. Rizki Marfira</li>
</ul>
<ul>
  <li>Jam operasional: Setiap hari pukul 08.00-18.00 WIB</li>
  <li>Kontak WhatsApp: 085391051302</li>
</ul>
```

**Comment by zainfathoni** [comment]
I think that would be complicated.
The easier way to fix it is to update the markup by updating the Google Docs itself.

**Comment by zainfathoni** [comment]
UPDATE for @ekafyi 

I and @resir014 just decided to go with the `/home-page` only implementation for now.
So you can move forward with your own PR using the old styling of the Google Docs home page.
So we can also merge this PR as the first version of the `/home-page` styling.

**Comment by ekafyi** [comment]
I pushed a small commit https://github.com/kawalcovid19/wargabantuwarga.com/pull/114/commits/399f0396d6783287c8edc28c99b351920db1020f before reading your last comment @zainfathoni . Should I revert it or just leave it there for now?

**Comment by zainfathoni** [comment]
You can leave it there for now @ekafyi, since it doesn't impact the `/home-page` at the moment.

**Comment by zainfathoni** [comment]
Thanks, anyway!
Sorry for the confusion, because there are too many things going on in parallel for the past few days. 😅

**Pull request merged**
