### PR TITLE
change copywriting from Cek sekarang to Telusuri sekarang

### LINKED ISSUE #573: Incorrect copywriting on Database CTA
## Description

On the Database CTA, the copywriting for the button is written as "Cek sekarang", where it should've been "Telusuri sekarang"

## Expected Behaviour

image

### PR DESCRIPTION
**Pull request by morezam**
Closes #573 

## Description

Change copywriting from Cek sekarang to Telusuri sekarang in homepage-start and its corresponding test file.

## Current Tasks

- Change copywriting from Cek sekarang to Telusuri sekarang in homepage-start
- Change copywriting from Cek sekarang to Telusuri sekarang in homepage-start.test

### CODE REVIEW

**Comment by resir014** [comment]
@morezam Please update the description according to the template before I can merge this.

**Comment by mazipan** [comment]
Please complete your PR with a proper description.
Link the issue number also.
We already set a template, it's have a purpose.

**Review by mazipan — CHANGES_REQUESTED** [review]
Block this PR, since have no proper description

**Review by mazipan — APPROVED** [review]

**Comment by resir014** [comment]
@morezam Test still failing. Please check again.

(protip: you can use `yarn test -u` to automatically update inline snapshots)

**Review by zainfathoni — APPROVED** [review]
LGTM 💯 

Thanks, @morezam! 🙏

**Comment by zainfathoni** [comment]
@all-contributors, please add @morezam for code.

**Comment by zainfathoni** [comment]
@all-contributors please add @morezam for code.

**Pull request merged**
