### PR TITLE
Move "Warga Bantu Warga" to the end of the page title

### LINKED ISSUE #233: Move "Warga Bantu Warga" to the back
> "Warga Bantu Warga" part takes too much space. How about moving it to the back instead?

It's on the default SEO set by @resir014 & @zainfathoni before.
On the common usecase, the identity sitename is usually on the right side.
After the main title.

So ya, I agree to move it out to the back.

I think it's better to work on another PR ya for fixing the composition of title

_Originally posted by @mazipan in https://github.com/kawalcovid19/wargabantuwarga.com/issues/227#issuecomment-883567404_

### PR DESCRIPTION
**Pull request by suliskh**
Closes #233 

## Description

Move "Warga Bantu Warga" to the end of the page title

## Screenshoots
- **Google Search Preview**
   image

- **Homepage**
   image

- **Province list page**
   image

- **Province detail page**
    image

- **Contact detail page**
   image

### CODE REVIEW

**Comment by mazipan** [comment]
Add screenshots for several pages ya:

- homepage/index page
- province list page
- province detail page
- contact detail page

**Comment by suliskh** [comment]
> Add screenshots for several pages ya:
> 
>     * homepage/index page
> 
>     * province list page
> 
>     * province detail page
> 
>     * contact detail page

Done! I've just put it in PR description, yah Mas @mazipan

**Comment by mazipan** [comment]
Just curious, this line https://github.com/kawalcovid19/wargabantuwarga.com/blob/main/pages/provinces/%5BprovinceSlug%5D/%5BcontactSlug%5D.tsx#L24 seems not well applied.

Maybe it's my bad, but can you help me to check, why it's not applied.

**Review by mazipan — APPROVED** [review]
Looks 🐐 to me

**Comment by suliskh** [comment]
> Just curious, this line https://github.com/kawalcovid19/wargabantuwarga.com/blob/main/pages/provinces/%5BprovinceSlug%5D/%5BcontactSlug%5D.tsx#L24 seems not well applied.
> 
> On Contact detail page
> 
> Maybe it's my bad, but can you help me to check, why it's not applied.

Yess mas @mazipan, it was actually my bad. This PR was behind the `main` branch 😅 .

Also, I fix the title on the contact detail page above by omitting the provider name if it's empty.

**Review by mazipan — APPROVED** [review]

**Comment by mazipan** [comment]
Thank you for the PR 🙌

**Comment by suliskh** [comment]
> Thank you for the PR 🙌

Thank you for guiding and reviewing it, Mas @mazipan :sungkem:

**Comment by zainfathoni** [comment]
Thank you for contributing this code, @suliskh. cc @all-contributors

**Comment by zainfathoni** [comment]
@all-contributors please add @suliskh for code.

**Pull request merged**
