### PR TITLE
fix: improve text color contrast

### LINKED ISSUE #572: Improve text colour contrast to improve accessibility
## Description

Several text/link elements in our Home page have low colour contrast:
- "Informasi Terbaru" dates
- "Informasi Terbaru" CTA (eg. _"Daftar vaksin Sinergi Sehat"_)
- Whatsapp contact CTA

See: ["Accessibility" section in the Lighthouse Report](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fwww.wargabantuwarga.com%2F#accessibility)

## Expected Behaviour

The text/link elements should have a contrast of at least `4.5`.

---

First-time contributor? See contributing guide here ([English](https://github.com/kawalcovid19/wargabantuwarga.com/blob/main/CONTRIBUTING.md) / [Bahasa Indonesia](https://github.com/kawalcovid19/wargabantuwarga.com/blob/main/CONTRIBUTING_ID.md)).

### PR DESCRIPTION
**Pull request by hendraaagil**
Closes #572 

## Description

Improve text color contrast to improve accessibility

<details>
  <summary>Detailed changes (click to expand)</summary>
  
  ---
    
  **"Informasi Terbaru" dates**
  
  - Before
  image
  
  - After
  image
  
  ---
  
  **"Informasi Terbaru" CTA**
  
  - Before
  image
  
  - After
  image
  
  ---
  
  **"Tambahkan info" CTA**
  
  - Before
  image
  
  - After
  image
  
  ---
  
  **Whatsapp contact CTA**
  
  - Before
  image
  
  - After
  image
  
</detail>

### CODE REVIEW

**Comment by zainfathoni** [comment]
Please write some test for the files that you changed, @hendraaagil, so that you can get this PR to pass the codecov/project check. 😁

**Comment by hendraaagil** [comment]
> Please write some test for the files that you changed, @hendraaagil, so that you can get this PR to pass the `codecov/project` check. 😁

How is it? I've never learn about testing before, I'm sorry 😅

**Comment by mazipan** [comment]
Can I get the screenshot of this changes in the description?
The before and the after.
It help us to know the exact point we should check

**Comment by mazipan** [comment]
Here is the LH report from this PR: https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1628255418477-29647.report.html

**Comment by mazipan** [comment]
All the color contrast issues are gone.

So it's good to me 👍

**Review by mazipan — APPROVED** [review]

**Comment by resir014** [comment]
> How is that? I've never learn about testing before, I'm sorry 😅

@hendraaagil [This comment](https://github.com/kawalcovid19/wargabantuwarga.com/pull/579#issuecomment-894189650) should show you which file/component you should add tests for. You can start by adding more tests for the file whose coverage dropped.

image

**Comment by zainfathoni** [comment]
> Already tried, but nothing changed 😅
> I need help, Mas @zainfathoni 🏳️

Test added, it should be passing the `codecov/project` check now. 😁

**Comment by hendraaagil** [comment]
Nice. Thank you Mas @zainfathoni 😄

**Pull request merged**
