### PR TITLE
Add home image banner field to Netlify CMS

### LINKED ISSUE #341: Enable image source URL to be updated from Netlify CMS as text fields
Currently, image source value is hardcoded in the Image component.

```js
<Image
  loader={cloudinaryLoader}
  src="v1626975062/hero_banner_pdx3xp.png"
  width={640}
  // other props
/>
```

Once we have fully adopted Netlify CMS for adding content, and particularly once we start #321 (which requires more images), we should add text input fields in Netlify CMS for each image. 

The Image component in frontend code should be updated to use `src` value from Netlify CMS data.

When an image needs to be updated, admins/editors may upload the image on Cloudinary then copy the source value to the text fields.

**Note:** This is a proposed issue for quick, temporary solution. A more powerful solution will be to [implement Cloudinary-Netlify CMS integration](https://www.netlifycms.org/docs/cloudinary/).

### PR DESCRIPTION
**Pull request by ekafyi**
Closes #341

Accidentally closed PR #364 due to deleted branch, recreate the PR here

## Description

Enable image source URL to be updated from Netlify CMS as text fields. Currently only for the Home Banner image, but can be replicated for other images should we need it.

### CODE REVIEW

**Comment by ekafyi** [comment]
What do you think of this approach for updating banner image, folks @kawalcovid19/wbw ?

1) Have **Banner Image** as a field in the Netlify CMS

Content_Manager

2) Render Home Banner from the field if not empty, else use current banner as fallback value: https://github.com/kawalcovid19/wargabantuwarga.com/pull/390/commits/d536318896d95939b1e058845fa557e77b94fcd8

---

**Notes**

- Short documentation/how-to for admins who need to update image:  https://gist.github.com/ekafyi/1a86987c111a96976309c12f047d43a9 (to copy and edit as needed)
- This is a quick temporary way to enable updating from the CMS if necessary. Next we can look into [Cloudinary-Netlify CMS integration](https://www.netlifycms.org/docs/cloudinary/).

**Review by zainfathoni — APPROVED** [review]
LGTM 💯 

Thanks, @ekafyi! 🙏

**Review by zainfathoni — CHANGES_REQUESTED** [review]
Unfortunately, based on Codecov, this code change reduces the code coverage project by `0.01%`, so we can't merge this project. 😅 
Could you please write a test for this `HomepageHeader` component, @ekafyi? 😁
Thanks! 🙏

**Review by zainfathoni — APPROVED** [review]
The test has been written, let's ship it! 🚢

**Comment by ekafyi** [comment]
> The test has been written, let's ship it! 🚢

nice, thanks! i didn't know now we need to add a test to pass CodeCov.

**Comment by zainfathoni** [comment]
> nice, thanks! I didn't know now we need to add a test to pass CodeCov.

Yes, we do. We have two gateways of keeping the code coverage threshold now:

1. Jest's coverage threshold, causing `yarn test:coverage` failure, which boils down to the **Unit and integration tests** CI check failure.
2. Codecov patch & project coverage thresholds, which don't tolerate any decrease in any of them.

**Pull request merged**
