### PR TITLE
#712 konseling page

### PR DESCRIPTION
**Pull request by RendyArthaP**
#712 Konseling Page

I already create this page, but i have no idea to add the navigation at navbar, maybe you guys can give me a feedback, and i will made that. This is my first time joining open source. Need more feedback to growing my skills. Thank you so much

### CODE REVIEW

**Comment by RendyArthaP** [comment]
Is there anybody can help me how to fix CI / Unit and integration tests (pull_request)?

i will try to fix that. Thank you

**Comment by svspicious** [comment]
I think it's already "work in progress" at #722 by @dekwahdimas.

To make sure your PR is not duplicated, before making PR make sure that is not being handled by another contributor. 
You can see at linked pull request section here
image

**Comment by RendyArthaP** [comment]
@svspicious oh okay mas. i just saw that still opened, and i saw their comment, his branch was deleted. so i just try to help. if this duplicate its okay. big sorry.

**Comment by resir014** [comment]
Duplicate of #722.

**Pull request closed without merging**
