### PR TITLE
design system - forms + input

### LINKED ISSUE #213: Design system - Forms & inputs
## Description

Clean up our form styles.

## Implementation Model

We redo our forms using [Tailwind's Forms plugin](https://github.com/tailwindlabs/tailwindcss-forms), and follow the base form designs [here](https://tailwindui.com/components/application-ui/forms/input-groups).

## Tasks

- [x] Install `@tailwindcss/forms` plugin
- [x] Input text element
- [x] Select element
- [x] Textarea element
- [x] Checkbox element

### PR DESCRIPTION
**Pull request by resir014**
Closes #213 

## Description

Compile all form styles into a unified design system.

## Current Tasks

- [x] Install `@tailwindcss/forms` plugin
- [x] Input text element
- [x] Select element
- [x] Textarea element
- [x] Checkbox element

### CODE REVIEW

**Review by mazipan — APPROVED** [review]
Looks solid 💪

Ship it!

**Comment by mazipan** [comment]
Conflict @resir014

**Review by zainfathoni — APPROVED** [review]
LGTM 💯 

Thanks a lot for working on the design system, @resir014! 🙏

**Comment by zainfathoni** [comment]
@all-contributors please add @resir014 for code and design.

**Pull request merged**
