### PR TITLE
feat(ui): open map button in list

### LINKED ISSUE #570: Add "buka peta" button in province list
## Description

I feel that _alamat_ shortcut is inconsistent we can open map in detail but not in the list. Also it can benefit user to suitable location to fasten their search without have go to detail page

Detail
image

List
image

## Tasks

- [ ] Add `OpenMapButton` component in province list

### PR DESCRIPTION
**Pull request by ramarahmanda**
Closes #570 

## Description

Add copy button in province list

## Current Tasks

- [x] Add OpenMapButton component in province list

### CODE REVIEW

**Comment by mazipan** [comment]
Please add the screenshot of this changes, the before and after.

**Comment by ramarahmanda** [comment]
@irfan-maulana-tkp 

## Before

image

## After

image

**Comment by mazipan** [comment]
Need to fix the codecov first, so it can be merge

**Review by zainfathoni — APPROVED** [review]
LGTM 💯 

Thanks, Mas @ramarahmanda! 🙏

**Comment by zainfathoni** [comment]
@all-contributors please add @ramarahmanda for ideas and code.

**Pull request merged**
