### PR TITLE
add empty state on provinces + contact list

### LINKED ISSUE #210: Add additional information when searching data result is none
## Description

Some users might be confused when they don't get information (because of no information could be served) or because no data related to the input.

## Implementation Model

image

## Tasks

- [ ]  Provide default UI component for no data

### LINKED ISSUE #216: Design system - Empty states
## Description

An empty state represents a container with no data in it.

## Implementation Model

[Tailwind UI](https://tailwindui.com/components/application-ui/feedback/empty-states#component-42930c785190e14c24b53ba822f4a92c) has an empty state component.

### PR DESCRIPTION
**Pull request by resir014**
Closes #210. Closes #216.

## Description

Add an empty state component and use it in the `ProvincesList` and `ContactList` when data is empty.

image

image

## Tasks

- [x] Provinces page
- [x] Contacts page

### CODE REVIEW

**Comment by mazipan** [comment]
Also happen on FAQ page

**Review by mazipan — APPROVED** [review]
Looks 🐐

**Comment by resir014** [comment]
> Also happen on FAQ page

@mazipan We can merge this now. I'll work on FAQ page in another PR.

**Review by zainfathoni — APPROVED** [review]
LGTM 💯 

Thanks, @resir014! 🙏

**Pull request merged**
