### PR TITLE
Use box mirroring instead of fetching and parsing

### PR DESCRIPTION
**Pull request by adityapurwa**
## Description

This PR contains changes that will remove the process of fetching and parsing data from WBW data sources and instead will use [WBW Box](https://wbw-box.lucentshard.com/) as the source of data. This will greatly increase the speeds of CI/CD as now it only depends on the network speed only instead of including the complexities of parsing.

image

## Current Tasks

N/A

### CODE REVIEW

**Review by zainfathoni — APPROVED** [review]
LGTM 💯 

Thanks for working on it @adityapurwa! 
However, let's wait for Mas @mazipan's review as well to see his opinion about it.

**Comment by zainfathoni** [comment]
I'm enabling the auto-merge because the benefits of speeding up the build time exceed the risks of getting failures from [WBW Box](https://wbw-box.lucentshard.com/). Speeding up the built time means faster GitHub Actions and Netlify builds.

**Comment by mazipan** [comment]
This is gold 🐐

**Comment by mazipan** [comment]
Do you know the source of this https://wbw-box.lucentshard.com?

**Comment by zainfathoni** [comment]
It's using this exact repository, he hosted it on his own server. 😁 
Here's the chat history to add some more context:

Screenshot 2021-07-24 at 22 27 53

**Pull request merged**
