### PR TITLE
Fix: selected filter url param not exist

### PR DESCRIPTION
**Pull request by ekamuktia**
Partial work for #393 

## Description

Fix search filter, use `filter` param instead of `filters` because `filters` only works if the data exists

### CODE REVIEW

**Comment by ekamuktia** [comment]
@zainfathoni I can only continue after 4 or 5pm today, so if #393 is urgent you can copy the added part or add the test code here 🙏

**Review by resir014 — APPROVED** [review]
Manual QA passed, just need to get the test coverage up to par. @zainfathoni @ekamuktia

**Comment by zainfathoni** [comment]
Finally, it passes the Codecov checks! 🎉

**Review by zainfathoni — APPROVED** [review]
LGTM 💯 

Thanks, Mbak @ekamuktia, for fixing this bug.

**Pull request merged**
