### PR TITLE
chore(security): add essential security headers

### LINKED ISSUE #608: Prevent clickjacking with `X-Frame-Options: DENY` header
## Description

The `X-Frame-Options` header tells the browser whether you want to allow your site to be framed or not. By preventing a browser from framing your site you can defend against attacks like clickjacking.

More info: https://scotthelme.co.uk/hardening-your-http-response-headers/#x-frame-options

## Implementation Model

[Click here](https://nextjs.org/docs/api-reference/next.config.js/headers) to learn how to set HTTP headers in Next.js. Example:

```js
// next.config.js

module.exports = {
  // ...

  async headers() {
    return [
      {
        source: "/(.*)",
        headers: [
          {
            key: "X-Frame-Options",
            value: "DENY"
          }
        ]
      }
    ];
  }
};
```

## Tasks

- [x] Add the `X-Frame-Options: DENY` header to `headers` on `next.config.js`

### LINKED ISSUE #609: Prevent content type sniffing with `X-Content-Type-Options: nosniff` header
## Description

The `X-Content-Type-Options` header stops a browser from trying to MIME-sniff the content type and forces it to stick with the declared content-type. The only valid value for this header is `X-Content-Type-Options: nosniff`.

More info: https://scotthelme.co.uk/hardening-your-http-response-headers/#x-content-type-options

## Implementation Model

[Click here](https://nextjs.org/docs/api-reference/next.config.js/headers) to learn how to set HTTP headers in Next.js. Example:

```js
// next.config.js

module.exports = {
  // ...

  async headers() {
    return [
      {
        source: "/(.*)",
        headers: [
          {
            key: "X-Content-Type-Options",
            value: "nosniff"
          }
        ]
      }
    ];
  }
};
```

## Tasks

- [x] Add the `X-Content-Type-Options: nosniff` header to `headers` on `next.config.js`

### PR DESCRIPTION
**Pull request by resir014**
Closes #608
Closes #609

## Description

Adds the following headers across all resources:

- `X-Content-Type-Options: nosniff` to prevent content type sniffing
- `X-Frame-Options: DENY` to prevent clickjacking

## Current Tasks

- [x] Add the essential security headers
- [x] Test on deploy preview (manually) that the headers are loaded correctly

### CODE REVIEW

**Review by mazipan — APPROVED** [review]

**Comment by resir014** [comment]
Hmm, headers don't seem to be loaded correctly. Need to figure this out.

image

**Comment by mazipan** [comment]
Try it @resir014.
Since usually I use vercel.json when deploying to Vercel

**Comment by resir014** [comment]
@mazipan Yep, turns out Netlify doesn't support the `headers` option in Next.js yet. We will have to resort to the `_headers` file in Netlify. https://github.com/netlify/netlify-plugin-nextjs/issues/150

**Comment by resir014** [comment]
@mazipan @zainfathoni Currently, only the header options on `netlify.toml` works. This comes with an unintended side effect that we have to duplicate the headers on both `netlify.toml` and `next.config.js`, in case Netlify supports the `headers` option on `next.config.js`

Shall we go with this for now?

**Comment by mazipan** [comment]
Okay from me about the duplication, since it's limitation from our infrastructure.

I just anxious with then CSP.
Since it might be block our 3rd party like GTM & GA.

Do we already test that it's not being blocked?

**Comment by resir014** [comment]
@mazipan We have not added CSP headers here yet, will be done on a separate PR.

**Pull request merged**
