### PR TITLE
Refactor useSearch from itemsjs to fuse.js

### LINKED ISSUE #197: Refactor use-search to use a properly-typed fuzzy-search library
## Brief

The current `useSearch()` implementation uses the `itemsjs` library, which has no proper typings. This leads to `useSearch()` being littered with `any` type annotations.

We want to avoid using `any` if possible. Therefore, we should migrate to a search library with proper typings (e.g. [fusejs](https://fusejs.io/)).

## Definition of done

- `use-search` properly migrated to a library with valid typings.
- All `any` are replaced by correct typings.

## Tasks

- [ ] Migrate to a properly typed fuzzy search library
- [ ] Refactor `use-search` to use fusejs and add proper typings

### PR DESCRIPTION
**Pull request by ekamuktia**
Closes #197 

## Description

Refactor useSearch from using `itemsjs` to properly typed `fuse.js`

## Current Tasks

- [ ] Refactor search function
- [ ] Add function to sort the result based on selected sort
- [ ] Restructure filter items
- [ ] Add function to create aggregate items for filter
- [ ] Change `any` to proper type
- [ ] Create index file after fetching

### CODE REVIEW

**Comment by resir014** [comment]
@ekamuktia Please update from main branch to merge in changes from #286.

**Comment by resir014** [comment]
@zainfathoni has finished implementing tests infrastructure. I think we can use this PR to start with writing unit tests for the `useSearch()` hook. @ekamuktia

**Comment by ekamuktia** [comment]
@resir014 @zainfathoni 
because search will be changed to typesense, I think this PR should be closed
also there's test problem with typesense search, the data is from index so I can't pass data from faqBuilder as the source

**Comment by resir014** [comment]
@ekamuktia You're right. Closing this in favour of the Typesense PR.

**Pull request closed without merging**
