### PR TITLE
style: hide NProgress spinner

### PR DESCRIPTION
**Pull request by resir014**
## Description

By default, NProgress has a spinner attached to the top right of the page which can be distracting when people look at the header menu button on mobile. https://github.com/kawalcovid19/wargabantuwarga.com/pull/500#issuecomment-889072610

image

This PR removes the spinner so that only the progress bar is visible.

### CODE REVIEW

**Comment by baraeb92** [comment]
Much better experience! Thank you @resir014

**Review by baraeb92 — APPROVED** [review]

**Review by mazipan — APPROVED** [review]
Solid!

**Comment by resir014** [comment]
@zainfathoni Need help with the coverage. -0.06% and I don't know how to properly test `_app.tsx`

**Comment by zainfathoni** [comment]
> @zainfathoni Need help with the coverage. -0.06% and I don't know how to properly test `_app.tsx`

Sure, I'll work on it later tonight. 😉

**Review by zainfathoni — APPROVED** [review]
LGTM 💯 

Thanks for fixing it, @resir014! 🙏

**Comment by zainfathoni** [comment]
I have written the tests for `_app.tsx`, however, it's too much hassle to pursue covering this line, unless we want to implement our own `router.events` API, which I think would be a waste of time. 😅 

Therefore, I'm merging this PR forcefully now.

**Pull request merged**
