### PR TITLE
feat(ui): check kebutuhan query in provinces page

### LINKED ISSUE #453: Add more reference text in Rumah Sakit & Donor Plasma queries
## Description

[Context](https://kawalcovid19.slack.com/archives/C0279E2Q99Q/p1627309956034600)

Screenshot 2021-07-26 at 23 11 05

image

image

## Implementation Model

If the query params satisfy both cases above, show the requested text

## Tasks

- [ ] Implement the additional reference text in the `Provinces` Page
- [ ] Render the additional reference text based on the query params
- [ ] Write the unit tests

### PR DESCRIPTION
**Pull request by ekafyi**
Closes #453

## Description

Add general (nationwide/not province specific) links in "Provinces" page for specific queries (Donor Plasma & Rumah Sakit). Objective: Enable user to quickly find general information, so it could be removed from the Home Page, improving its readability & user-friendliness.

- https://deploy-preview-454--wargabantuwarga.netlify.app/provinces?kebutuhan=Rumah%20sakit
- https://deploy-preview-454--wargabantuwarga.netlify.app/provinces?kebutuhan=Donor%20plasma

## Current Tasks

- [x] Render container in Province page containing relevant queries
- [x] Add content for kebutuhan=Rumah sakit 
- [x] Add content for kebutuhan=Donor plasma
- [x] Improve styling, make reusable UI component
- [x] Write UI test

### CODE REVIEW

**Comment by ekafyi** [comment]
_*brb opening old bookmarks on how to write UI tests_ 😬

**Comment by mazipan** [comment]
I think we can also split from our `fechers`
Currently we only generate one big JSON file.
How if we keep the big one, but also generate a spesific JSON file.

e.g: 
- Data by Category for all provinces (misalnya: data rumah sakit seluruh Indonesia
- Data per Category per Province???

With this, we can also have a possibility to generate another page, like mentioned in this ticket.

**Comment by zainfathoni** [comment]
> _*brb opening old bookmarks on how to write UI tests_ 😬

Maybe [my talk here](https://zainf.dev/confident-react-testing) could be helpful in understanding the basic principles 😁

**Review by zainfathoni — APPROVED** [review]
LGTM 💯 

Thanks, @ekafyi!

**Pull request merged**
