### PR TITLE
Implement an adequate styling for the Netlify CMS-managed home page

### LINKED ISSUE #38: Implement an adequate styling for the Netlify CMS-managed home page
## Tasks

- [x] #114
- [x] #190

### PR DESCRIPTION
**Pull request by emer7**
Closes #38 

## Current Tasks

- [ ] 
- [ ] 
- [ ]

### CODE REVIEW

**Comment by zainfathoni** [comment]
Do you have any ETA for this, @emer7?
We might need this to be implemented soon, so I might create another PR to solve this #38 issue.

**Comment by emer7** [comment]
Hi sorry I am quite occupied for the whole weekend.

I just pulled the latest update, it seems styling has been implemented using the `prose` class of `tailwindcss/typography`

So I think this PR is not relevant anymore and the issue can be closed already 😅, unless the issue means something else

Apology for my delay

**Comment by zainfathoni** [comment]
No worries, there's a remaining task, which is to customize the styling to make it looks better.
If you don't have any time for this in the next 1-2 days, I'll work on it, then. Thanks!

**Comment by emer7** [comment]
For further custom styling, I think best leave to you to decide on the styling. My original plan is to do exactly what is implemented now (that is applying a layout / standardized styling targeting the parsed-to-HTML markdown content). I will work on other issue instead. Thank you.

**Comment by zainfathoni** [comment]
Nice, thanks, @emer7! 🙏

More issues are coming! I'm creating some of them now. 😁

**Pull request closed without merging**
