### PR TITLE
Update Kontak Darurat Page “emergency_contacts”

### PR DESCRIPTION
**Pull request by zainfathoni**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by mazipan** [comment]
Can we publish this @dekwahdimas?

**Comment by dekwahdimas** [comment]
Yes, I was waiting for a review from anyone else on Netlify CMS actually if its good enough.

**Comment by mazipan** [comment]
Usually, I just publish it, after looking the preview domain

**Comment by dekwahdimas** [comment]
Ah, I thought I didn't have rights to publish it myself so I'm waiting for a review first. Okay then, I'm going to publish it now. Thank you, Mas

**Pull request merged**
