### PR TITLE
UI/temp Home Page styling

### LINKED ISSUE #118: (UI improvement) Remove borders from Google Docs-generated Home Page
## Description

Remove borders from Google Docs-generated "tables" in Home Page UI and replace it with more visually pleasing separator.

from:
Screen Shot 2021-07-17 at 22 50 47

to:
Screen Shot 2021-07-17 at 22 50 35

## Implementation Model

Apply custom styling.

Ready to submit PR if approved.

### PR DESCRIPTION
**Pull request by ekafyi**
Closes #118

## Description

Style Google Docs-generated "tables" in Home Page UI.

I implement it in global styles and use techniques not considered good practice because the markup is outside our codebase. I also modified `.stylelintrc` to allow `%` unit because otherwise it would not be possible to create the pseudo element for the light gray "border".

Edits welcome of course.

### CODE REVIEW

**Comment by ekafyi** [comment]
welp i didn't see this https://github.com/kawalcovid19/wargabantuwarga.com/issues/118#issuecomment-881928340

will check your PR first and add to that.

**Review by zainfathoni — APPROVED** [review]
LGTM 💯 

Thanks, @ekafyi !

**Comment by ekafyi** [comment]
I don't even know why the generated links are marked as "uncrawlable" by the Lighthouse plugin. These are regular `<a>` element with `href` attribute and no onclick event.

I assume it's because of the parameters?

example:

```html
<a class="c10" href="https://www.google.com/url?q=https://docs.google.com/forms/d/e/1FAIpQLScMT8SfADFTMlJ07nHY043fYN-eTBJi1WR6zmnadIwtdoNWlA/viewform&amp;sa=D&amp;source=editors&amp;ust=1626548775397000&amp;usg=AOvVaw3_XY_sg2BnZyIFrgCnGthr">ajukan bantuan kebutuhan pokok jika positif Covid-19 dengan isi formulir di sini.</a>
```

**Comment by zainfathoni** [comment]
I think that was because we're hopping to Google's URL before visiting the actual destination URL. 😅

**Pull request merged**
